export const product = [
    {
        "id": 1,
        "code": "APP001",
        "name": "CRISPY CHICKEN BITES",
        "active": true,
        "image": "/public/images/CRISPY CHICKEN BITES.jpg",
        "openPrice": false,
        "price1": 47500,
        "price2": 0,
        "price3": 0,
        "purchased": false,
        "purchasedToInventoryConversion": 0,
        "purchasePrice": 0,
        "purchaseUom": "",
        "recipeUom": "",
        "averageCost": 0,
        "barcode": "0",
        "serviceCharge": true,
        "tax": true,
        "category_id": 1,
        "salesWarehouse_id": 1,
        "createdAt": "2022-08-22T13:52:13.000Z",
        "updatedAt": "2022-08-22T13:52:13.000Z"
    },
    {
        "id": 2,
        "code": "APP002",
        "name": "FRENCH FRIES",
        "active": true,
        "image": "uploads/FRENCH FRIES.jpg",
        "openPrice": false,
        "price1": 28500,
        "price2": 0,
        "price3": 0,
        "purchased": false,
        "purchasedToInventoryConversion": 0,
        "purchasePrice": 0,
        "purchaseUom": "",
        "recipeUom": "",
        "averageCost": 0,
        "barcode": "0",
        "serviceCharge": true,
        "tax": true,
        "category_id": 1,
        "salesWarehouse_id": 1,
        "createdAt": "2022-08-22T13:52:13.000Z",
        "updatedAt": "2022-08-22T13:52:13.000Z"
    },
    {
        "id": 3,
        "code": "APP003",
        "name": "POTATO PARMESAN CHEESE",
        "active": true,
        "image": "uploads/POTATO PARMESAN CHEESE.jpg",
        "openPrice": false,
        "price1": 39500,
        "price2": 0,
        "price3": 0,
        "purchased": false,
        "purchasedToInventoryConversion": 0,
        "purchasePrice": 0,
        "purchaseUom": "",
        "recipeUom": "",
        "averageCost": 0,
        "barcode": "0",
        "serviceCharge": true,
        "tax": true,
        "category_id": 1,
        "salesWarehouse_id": 1,
        "createdAt": "2022-08-22T13:52:13.000Z",
        "updatedAt": "2022-08-22T13:52:13.000Z"
    },
    {
        "id": 4,
        "code": "APP004",
        "name": "CRISPY NACHOS",
        "active": true,
        "image": "uploads/CRISPY NACHOS.jpg",
        "openPrice": false,
        "price1": 35500,
        "price2": 0,
        "price3": 0,
        "purchased": false,
        "purchasedToInventoryConversion": 0,
        "purchasePrice": 0,
        "purchaseUom": "",
        "recipeUom": "",
        "averageCost": 0,
        "barcode": "0",
        "serviceCharge": true,
        "tax": true,
        "category_id": 1,
        "salesWarehouse_id": 1,
        "createdAt": "2022-08-22T13:52:13.000Z",
        "updatedAt": "2022-08-22T13:52:13.000Z"
    },
    {
        "id": 5,
        "code": "APP005",
        "name": "FRUITS CHEESE QUASADILLAS",
        "active": true,
        "image": "uploads/FRUITS CHEESE QUASADILLAS.jpg",
        "openPrice": false,
        "price1": 42500,
        "price2": 0,
        "price3": 0,
        "purchased": false,
        "purchasedToInventoryConversion": 0,
        "purchasePrice": 0,
        "purchaseUom": "",
        "recipeUom": "",
        "averageCost": 0,
        "barcode": "0",
        "serviceCharge": true,
        "tax": true,
        "category_id": 1,
        "salesWarehouse_id": 1,
        "createdAt": "2022-08-22T13:52:13.000Z",
        "updatedAt": "2022-08-22T13:52:13.000Z"
    },
    {
        "id": 6,
        "code": "APP006",
        "name": "GARLIC BREAD",
        "active": true,
        "image": "uploads/GARLIC BREAD.jpg",
        "openPrice": false,
        "price1": 28500,
        "price2": 0,
        "price3": 0,
        "purchased": false,
        "purchasedToInventoryConversion": 0,
        "purchasePrice": 0,
        "purchaseUom": "",
        "recipeUom": "",
        "averageCost": 0,
        "barcode": "0",
        "serviceCharge": true,
        "tax": true,
        "category_id": 1,
        "salesWarehouse_id": 1,
        "createdAt": "2022-08-22T13:52:13.000Z",
        "updatedAt": "2022-08-22T13:52:13.000Z"
    },
    {
        "id": 7,
        "code": "APP007",
        "name": "FISH & CHIPS",
        "active": true,
        "image": "uploads/FISH & CHIPS.jpg",
        "openPrice": false,
        "price1": 49500,
        "price2": 0,
        "price3": 0,
        "purchased": false,
        "purchasedToInventoryConversion": 0,
        "purchasePrice": 0,
        "purchaseUom": "",
        "recipeUom": "",
        "averageCost": 0,
        "barcode": "0",
        "serviceCharge": true,
        "tax": true,
        "category_id": 1,
        "salesWarehouse_id": 1,
        "createdAt": "2022-08-22T13:52:13.000Z",
        "updatedAt": "2022-08-22T13:52:13.000Z"
    },
    {
        "id": 8,
        "code": "APP008",
        "name": "SALMON BRUSCHETTA",
        "active": true,
        "image": "uploads/SALMON BRUSCHETTA.jpg",
        "openPrice": false,
        "price1": 39500,
        "price2": 0,
        "price3": 0,
        "purchased": false,
        "purchasedToInventoryConversion": 0,
        "purchasePrice": 0,
        "purchaseUom": "",
        "recipeUom": "",
        "averageCost": 0,
        "barcode": "0",
        "serviceCharge": true,
        "tax": true,
        "category_id": 1,
        "salesWarehouse_id": 1,
        "createdAt": "2022-08-22T13:52:13.000Z",
        "updatedAt": "2022-08-22T13:52:13.000Z"
    },
    {
        "id": 9,
        "code": "APP009",
        "name": "CHICKEN BURITOS",
        "active": true,
        "image": "uploads/CHICKEN BURITOS.jpg",
        "openPrice": false,
        "price1": 39500,
        "price2": 0,
        "price3": 0,
        "purchased": false,
        "purchasedToInventoryConversion": 0,
        "purchasePrice": 0,
        "purchaseUom": "",
        "recipeUom": "",
        "averageCost": 0,
        "barcode": "0",
        "serviceCharge": true,
        "tax": true,
        "category_id": 1,
        "salesWarehouse_id": 1,
        "createdAt": "2022-08-22T13:52:13.000Z",
        "updatedAt": "2022-08-22T13:52:13.000Z"
    },
    {
        "id": 10,
        "code": "APP010",
        "name": "KAWA EBI",
        "active": true,
        "image": "uploads/KAWA EBI.jpg",
        "openPrice": false,
        "price1": 28500,
        "price2": 0,
        "price3": 0,
        "purchased": false,
        "purchasedToInventoryConversion": 0,
        "purchasePrice": 0,
        "purchaseUom": "",
        "recipeUom": "",
        "averageCost": 0,
        "barcode": "0",
        "serviceCharge": true,
        "tax": true,
        "category_id": 1,
        "salesWarehouse_id": 1,
        "createdAt": "2022-08-22T13:52:13.000Z",
        "updatedAt": "2022-08-22T13:52:13.000Z"
    },
    {
        "id": 11,
        "code": "APP011",
        "name": "PISANG KIPAS",
        "active": true,
        "image": "uploads/PISANG KIPAS.jpg",
        "openPrice": false,
        "price1": 28500,
        "price2": 0,
        "price3": 0,
        "purchased": false,
        "purchasedToInventoryConversion": 0,
        "purchasePrice": 0,
        "purchaseUom": "",
        "recipeUom": "",
        "averageCost": 0,
        "barcode": "0",
        "serviceCharge": true,
        "tax": true,
        "category_id": 1,
        "salesWarehouse_id": 1,
        "createdAt": "2022-08-22T13:52:13.000Z",
        "updatedAt": "2022-08-22T13:52:13.000Z"
    },
    {
        "id": 12,
        "code": "APP012",
        "name": "BEEF BURGER",
        "active": true,
        "image": "uploads/BEEF BURGER.jpg",
        "openPrice": false,
        "price1": 42500,
        "price2": 0,
        "price3": 0,
        "purchased": false,
        "purchasedToInventoryConversion": 0,
        "purchasePrice": 0,
        "purchaseUom": "",
        "recipeUom": "",
        "averageCost": 0,
        "barcode": "0",
        "serviceCharge": true,
        "tax": true,
        "category_id": 1,
        "salesWarehouse_id": 1,
        "createdAt": "2022-08-22T13:52:13.000Z",
        "updatedAt": "2022-08-22T13:52:13.000Z"
    },
    {
        "id": 13,
        "code": "SAL001",
        "name": "FRUITS SALAD",
        "active": true,
        "image": "uploads/FRUITS SALAD.jpg",
        "openPrice": false,
        "price1": 39500,
        "price2": 0,
        "price3": 0,
        "purchased": false,
        "purchasedToInventoryConversion": 0,
        "purchasePrice": 0,
        "purchaseUom": "",
        "recipeUom": "",
        "averageCost": 0,
        "barcode": "0",
        "serviceCharge": true,
        "tax": true,
        "category_id": 2,
        "salesWarehouse_id": 1,
        "createdAt": "2022-08-22T13:52:13.000Z",
        "updatedAt": "2022-08-22T13:52:13.000Z"
    },
    {
        "id": 14,
        "code": "SAL002",
        "name": "GARDENIA SALAD",
        "active": true,
        "image": "uploads/GARDENIA SALAD.jpg",
        "openPrice": false,
        "price1": 39500,
        "price2": 0,
        "price3": 0,
        "purchased": false,
        "purchasedToInventoryConversion": 0,
        "purchasePrice": 0,
        "purchaseUom": "",
        "recipeUom": "",
        "averageCost": 0,
        "barcode": "0",
        "serviceCharge": true,
        "tax": true,
        "category_id": 2,
        "salesWarehouse_id": 1,
        "createdAt": "2022-08-22T13:52:13.000Z",
        "updatedAt": "2022-08-22T13:52:13.000Z"
    },
    {
        "id": 15,
        "code": "PIZ001",
        "name": "PIZZA SWEET CORN",
        "active": true,
        "image": "uploads/PIZZA SWEET CORN.jpg",
        "openPrice": false,
        "price1": 69500,
        "price2": 0,
        "price3": 0,
        "purchased": false,
        "purchasedToInventoryConversion": 0,
        "purchasePrice": 0,
        "purchaseUom": "",
        "recipeUom": "",
        "averageCost": 0,
        "barcode": "0",
        "serviceCharge": true,
        "tax": true,
        "category_id": 3,
        "salesWarehouse_id": 1,
        "createdAt": "2022-08-22T13:52:13.000Z",
        "updatedAt": "2022-08-22T13:52:13.000Z"
    },
    {
        "id": 16,
        "code": "PIZ002",
        "name": "PIZZA CHICKEN OLIVE",
        "active": true,
        "image": "uploads/PIZZA CHICKEN OLIVE.jpg",
        "openPrice": false,
        "price1": 69500,
        "price2": 0,
        "price3": 0,
        "purchased": false,
        "purchasedToInventoryConversion": 0,
        "purchasePrice": 0,
        "purchaseUom": "",
        "recipeUom": "",
        "averageCost": 0,
        "barcode": "0",
        "serviceCharge": true,
        "tax": true,
        "category_id": 3,
        "salesWarehouse_id": 1,
        "createdAt": "2022-08-22T13:52:13.000Z",
        "updatedAt": "2022-08-22T13:52:13.000Z"
    },
    {
        "id": 17,
        "code": "PIZ003",
        "name": "PIZZA MUSHROOM",
        "active": true,
        "image": "uploads/PIZZA MUSHROOM.jpg",
        "openPrice": false,
        "price1": 69500,
        "price2": 0,
        "price3": 0,
        "purchased": false,
        "purchasedToInventoryConversion": 0,
        "purchasePrice": 0,
        "purchaseUom": "",
        "recipeUom": "",
        "averageCost": 0,
        "barcode": "0",
        "serviceCharge": true,
        "tax": true,
        "category_id": 3,
        "salesWarehouse_id": 1,
        "createdAt": "2022-08-22T13:52:13.000Z",
        "updatedAt": "2022-08-22T13:52:13.000Z"
    },
    {
        "id": 18,
        "code": "PIZ004",
        "name": "PIZZA TOMATO CHEESE",
        "active": true,
        "image": "uploads/PIZZA TOMATO CHEESE.jpg",
        "openPrice": false,
        "price1": 28500,
        "price2": 0,
        "price3": 0,
        "purchased": false,
        "purchasedToInventoryConversion": 0,
        "purchasePrice": 0,
        "purchaseUom": "",
        "recipeUom": "",
        "averageCost": 0,
        "barcode": "0",
        "serviceCharge": true,
        "tax": true,
        "category_id": 3,
        "salesWarehouse_id": 1,
        "createdAt": "2022-08-22T13:52:13.000Z",
        "updatedAt": "2022-08-22T13:52:13.000Z"
    },
    {
        "id": 19,
        "code": "PAS001",
        "name": "PASTA AGLIO OLIO PRAWN",
        "active": true,
        "image": "uploads/PASTA AGLIO OLIO PRAWN.jpg",
        "openPrice": false,
        "price1": 59500,
        "price2": 0,
        "price3": 0,
        "purchased": false,
        "purchasedToInventoryConversion": 0,
        "purchasePrice": 0,
        "purchaseUom": "",
        "recipeUom": "",
        "averageCost": 0,
        "barcode": "0",
        "serviceCharge": true,
        "tax": true,
        "category_id": 4,
        "salesWarehouse_id": 1,
        "createdAt": "2022-08-22T13:52:13.000Z",
        "updatedAt": "2022-08-22T13:52:13.000Z"
    },
    {
        "id": 20,
        "code": "PAS002",
        "name": "PASTA AGLIO OLIO SALMON",
        "active": true,
        "image": "uploads/PASTA AGLIO OLIO SALMON.jpg",
        "openPrice": false,
        "price1": 67500,
        "price2": 0,
        "price3": 0,
        "purchased": false,
        "purchasedToInventoryConversion": 0,
        "purchasePrice": 0,
        "purchaseUom": "",
        "recipeUom": "",
        "averageCost": 0,
        "barcode": "0",
        "serviceCharge": true,
        "tax": true,
        "category_id": 4,
        "salesWarehouse_id": 1,
        "createdAt": "2022-08-22T13:52:13.000Z",
        "updatedAt": "2022-08-22T13:52:13.000Z"
    },
    {
        "id": 21,
        "code": "PAS003",
        "name": "PASTA BOLOGNAISE",
        "active": true,
        "image": "uploads/PASTA BOLOGNAISE.jpg",
        "openPrice": false,
        "price1": 59500,
        "price2": 0,
        "price3": 0,
        "purchased": false,
        "purchasedToInventoryConversion": 0,
        "purchasePrice": 0,
        "purchaseUom": "",
        "recipeUom": "",
        "averageCost": 0,
        "barcode": "0",
        "serviceCharge": true,
        "tax": true,
        "category_id": 4,
        "salesWarehouse_id": 1,
        "createdAt": "2022-08-22T13:52:13.000Z",
        "updatedAt": "2022-08-22T13:52:13.000Z"
    },
    {
        "id": 22,
        "code": "PAS004",
        "name": "PASTA ALFREDO",
        "active": true,
        "image": "uploads/PASTA ALFREDO.jpg",
        "openPrice": false,
        "price1": 59500,
        "price2": 0,
        "price3": 0,
        "purchased": false,
        "purchasedToInventoryConversion": 0,
        "purchasePrice": 0,
        "purchaseUom": "",
        "recipeUom": "",
        "averageCost": 0,
        "barcode": "0",
        "serviceCharge": true,
        "tax": true,
        "category_id": 4,
        "salesWarehouse_id": 1,
        "createdAt": "2022-08-22T13:52:13.000Z",
        "updatedAt": "2022-08-22T13:52:13.000Z"
    },
    {
        "id": 23,
        "code": "PAS005",
        "name": "PASTA MEAT BALLS",
        "active": true,
        "image": "uploads/PASTA MEAT BALLS.jpg",
        "openPrice": false,
        "price1": 59500,
        "price2": 0,
        "price3": 0,
        "purchased": false,
        "purchasedToInventoryConversion": 0,
        "purchasePrice": 0,
        "purchaseUom": "",
        "recipeUom": "",
        "averageCost": 0,
        "barcode": "0",
        "serviceCharge": true,
        "tax": true,
        "category_id": 4,
        "salesWarehouse_id": 1,
        "createdAt": "2022-08-22T13:52:13.000Z",
        "updatedAt": "2022-08-22T13:52:13.000Z"
    },
    {
        "id": 24,
        "code": "TEA001",
        "name": "BRITISH TEA",
        "active": true,
        "image": "uploads/PASTA MEAT BALLS.jpg",
        "openPrice": false,
        "price1": 15500,
        "price2": 0,
        "price3": 0,
        "purchased": false,
        "purchasedToInventoryConversion": 0,
        "purchasePrice": 0,
        "purchaseUom": "",
        "recipeUom": "",
        "averageCost": 0,
        "barcode": "0",
        "serviceCharge": true,
        "tax": true,
        "category_id": 7,
        "salesWarehouse_id": 1,
        "createdAt": "2022-08-22T13:52:13.000Z",
        "updatedAt": "2022-08-22T13:52:13.000Z"
    },
    {
        "id": 25,
        "code": "TEA002",
        "name": "CHAMOMILE TEA",
        "active": true,
        "image": "uploads/CHAMOMILE TEA.jpg",
        "openPrice": false,
        "price1": 17500,
        "price2": 0,
        "price3": 0,
        "purchased": false,
        "purchasedToInventoryConversion": 0,
        "purchasePrice": 0,
        "purchaseUom": "",
        "recipeUom": "",
        "averageCost": 0,
        "barcode": "0",
        "serviceCharge": true,
        "tax": true,
        "category_id": 7,
        "salesWarehouse_id": 1,
        "createdAt": "2022-08-22T13:52:13.000Z",
        "updatedAt": "2022-08-22T13:52:13.000Z"
    },
    {
        "id": 26,
        "code": "TEA003",
        "name": "PEPPERMINT TEA",
        "active": true,
        "image": "uploads/PEPPERMINT TEA.jpg",
        "openPrice": false,
        "price1": 17500,
        "price2": 0,
        "price3": 0,
        "purchased": false,
        "purchasedToInventoryConversion": 0,
        "purchasePrice": 0,
        "purchaseUom": "",
        "recipeUom": "",
        "averageCost": 0,
        "barcode": "0",
        "serviceCharge": true,
        "tax": true,
        "category_id": 7,
        "salesWarehouse_id": 1,
        "createdAt": "2022-08-22T13:52:13.000Z",
        "updatedAt": "2022-08-22T13:52:13.000Z"
    },
    {
        "id": 27,
        "code": "TEA004",
        "name": "ICED TEA",
        "active": true,
        "image": "uploads/ICED TEA.jpg",
        "openPrice": false,
        "price1": 15500,
        "price2": 0,
        "price3": 0,
        "purchased": false,
        "purchasedToInventoryConversion": 0,
        "purchasePrice": 0,
        "purchaseUom": "",
        "recipeUom": "",
        "averageCost": 0,
        "barcode": "0",
        "serviceCharge": true,
        "tax": true,
        "category_id": 7,
        "salesWarehouse_id": 1,
        "createdAt": "2022-08-22T13:52:13.000Z",
        "updatedAt": "2022-08-22T13:52:13.000Z"
    },
    {
        "id": 28,
        "code": "TEA005",
        "name": "COLD BREWED ICED TEA",
        "active": true,
        "image": "uploads/COLD BREWED ICED TEA.jpg",
        "openPrice": false,
        "price1": 15500,
        "price2": 0,
        "price3": 0,
        "purchased": false,
        "purchasedToInventoryConversion": 0,
        "purchasePrice": 0,
        "purchaseUom": "",
        "recipeUom": "",
        "averageCost": 0,
        "barcode": "0",
        "serviceCharge": true,
        "tax": true,
        "category_id": 7,
        "salesWarehouse_id": 1,
        "createdAt": "2022-08-22T13:52:13.000Z",
        "updatedAt": "2022-08-22T13:52:13.000Z"
    },
    {
        "id": 29,
        "code": "TEA006",
        "name": "ICED LONGAN TEA",
        "active": true,
        "image": "uploads/ICED LONGAN TEA.jpg",
        "openPrice": false,
        "price1": 15500,
        "price2": 0,
        "price3": 0,
        "purchased": false,
        "purchasedToInventoryConversion": 0,
        "purchasePrice": 0,
        "purchaseUom": "",
        "recipeUom": "",
        "averageCost": 0,
        "barcode": "0",
        "serviceCharge": true,
        "tax": true,
        "category_id": 7,
        "salesWarehouse_id": 1,
        "createdAt": "2022-08-22T13:52:13.000Z",
        "updatedAt": "2022-08-22T13:52:13.000Z"
    },
    {
        "id": 30,
        "code": "CIG001",
        "name": "SAMPOERNA",
        "active": true,
        "image": "uploads/SAMPOERNA.jpg",
        "openPrice": false,
        "price1": 36500,
        "price2": 0,
        "price3": 0,
        "purchased": false,
        "purchasedToInventoryConversion": 0,
        "purchasePrice": 0,
        "purchaseUom": "",
        "recipeUom": "",
        "averageCost": 0,
        "barcode": "0",
        "serviceCharge": true,
        "tax": true,
        "category_id": 13,
        "salesWarehouse_id": 1,
        "createdAt": "2022-08-22T13:52:13.000Z",
        "updatedAt": "2022-08-22T13:52:13.000Z"
    }
]